package BankAccountLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;

public class AccountTransfer_Constraints extends BaseConstraintsDescriptor {
  public AccountTransfer_Constraints() {
    super(MetaAdapterFactory.getConcept(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, "BankAccountLanguage.structure.AccountTransfer"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f5ab3cL, "amount"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f5ab3cL), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "amount";
        return ((SPropertyOperations.getInteger(propertyValue)) > 0) && (SPropertyOperations.getInteger(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f5b0b6L, "transfer_from")), MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea51L, "id")) != SPropertyOperations.getInteger(SLinkOperations.getTarget(node, MetaAdapterFactory.getReferenceLink(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f6b56fL, "transfer_to")), MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea51L, "id")));
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f986b8L, "id"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f986b8L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "id";
        return (SPropertyOperations.getInteger(propertyValue)) > 0;
      }
    });
    return properties;
  }
  @Override
  protected Map<SReferenceLink, ReferenceConstraintsDescriptor> getSpecifiedReferences() {
    Map<SReferenceLink, ReferenceConstraintsDescriptor> references = new HashMap<SReferenceLink, ReferenceConstraintsDescriptor>();
    references.put(MetaAdapterFactory.getReferenceLink(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f6b56fL, "transfer_to"), new BaseReferenceConstraintsDescriptor(MetaIdFactory.refId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f5ab39L, 0x3b35fc9970f6b56fL), this) {});
    return references;
  }
}
