package BankAccountLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Map;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Account_Constraints extends BaseConstraintsDescriptor {
  public Account_Constraints() {
    super(MetaAdapterFactory.getConcept(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, "BankAccountLanguage.structure.Account"));
  }

  @Override
  protected Map<SProperty, PropertyConstraintsDescriptor> getSpecifiedProperties() {
    Map<SProperty, PropertyConstraintsDescriptor> properties = new HashMap<SProperty, PropertyConstraintsDescriptor>();
    properties.put(MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea51L, "id"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea51L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "id";
        return (SPropertyOperations.getInteger(propertyValue)) > 0;
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea53L, "balance"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea53L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "balance";
        return (SPropertyOperations.getInteger(propertyValue)) > 0;
      }
    });
    properties.put(MetaAdapterFactory.getProperty(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea52L, "owner"), new BasePropertyConstraintsDescriptor(MetaIdFactory.propId(0xa149b9dcff0647ecL, 0xa44db3d8f112f02eL, 0x3b35fc9970f8ea50L, 0x3b35fc9970f8ea52L), this) {
      @Override
      public boolean hasOwnValidator() {
        return true;
      }
      @Override
      public boolean validateValue(SNode node, String propertyValue) {
        String propertyName = "owner";
        return !((SPropertyOperations.getString(propertyValue)).isEmpty());
      }
    });
    return properties;
  }
}
